"""Builds a DRAFT fare-review notice document from a flag.

Read this before extending anything here: **this module builds a document
and returns it. It does not, and must never, send one.** There is no email
function, no webhook, no outbound request, and no "sent" state anywhere in
this feature. The reason is not caution for its own sake — it is that this
project has no regulatory authority, no verified identity of who is
operating it, and no relationship with DGCA or MoCA. A prototype that
dispatched correspondence to an airline as though it did would be
misrepresenting itself, which is the same failure this codebase already
refuses elsewhere when it declines to compute a "justified/unjustified"
verdict on a fare (see app.index.financial_context).

So the division of labour is explicit: this system produces evidence,
assembled from real dated data with its method stated. A human regulator
reads it, decides whether it warrants anything at all, and — if so — acts
through their own official channels, on their own letterhead, under their
own authority. Every field below exists to make that human's job easier and
their judgement better-informed. None of it exists to pre-empt that
judgement.

backend/tests/test_regulator_boundaries.py enforces this structurally: it
fails the build if any function or output key in this feature starts
looking like autonomous dispatch or a fairness verdict.
"""
from __future__ import annotations

from sqlalchemy.orm import Session

from app.db.models import RegulatorFareFlag
from app.index.anomaly_detection import (
    ANOMALY_Z_THRESHOLD,
    MIN_HISTORY_DAYS_FOR_ANOMALY_CHECK,
    MIN_PCT_ABOVE_BASELINE_FOR_FLAG,
    why_context_for_flag,
)
from app.scraper.compliance import ComplianceGate

DOCUMENT_TYPE = "DRAFT_FARE_REVIEW_NOTICE"

DRAFT_DISCLAIMER = (
    "DRAFT — NOT AN OFFICIAL COMMUNICATION. Generated by a prototype statistical "
    "monitoring tool. Has not been reviewed, approved, or issued by any regulator, "
    "and carries no legal or regulatory authority. Must not be sent to any airline "
    "or third party as-is."
)

BOUNDARY_NOTICE = (
    "This document places real, dated observations side by side so a human reviewer "
    "can form their own judgement. It contains no finding that any fare was unlawful, "
    "excessive, or improper — this system does not compute such a finding and cannot. "
    "The statistical flag means only that one collected fare departed from that same "
    "route, carrier and booking window's own recent history by more than the stated "
    "threshold; ordinary commercial factors may fully account for it. Any regulatory "
    "step arising from this document must be decided and issued by an authorised "
    "official through official channels. This tool issues nothing and sends nothing."
)

DETECTION_METHOD_NOTE = (
    "Median/MAD robust z-score against the same route+carrier+booking-window's own "
    "prior real daily fares: z = 0.6745 x (observed - baseline_median) / baseline_MAD, "
    f"flagged when z > {ANOMALY_Z_THRESHOLD} (the Iglewicz & Hoaglin 1993 convention) "
    f"AND the fare is at least {MIN_PCT_ABOVE_BASELINE_FOR_FLAG:.0f}% above that baseline "
    "median (both conditions required — on a very stable route a trivial increase can "
    "score a high z, which is statistically unusual but not materially significant). "
    f"Requires at least {MIN_HISTORY_DAYS_FOR_ANOMALY_CHECK} prior real days and a "
    "non-zero baseline spread, otherwise no flag is raised. This is the same test and "
    "the same threshold app.pipeline.clean.robust_outlier_mask already applies to "
    "screen scraped data, reused here across days rather than within one scrape run, "
    "and restricted to the elevated side only. Fares below a route's own history are "
    "never flagged."
)


def build_draft_notice(
    session: Session, flag: RegulatorFareFlag, gate: ComplianceGate | None = None
) -> dict:
    """Assembles the draft document for one flag. Pure — reads, returns, and
    changes nothing.

    The flag's own statistical figures are taken as stored (frozen at
    detection time, so a later day's shifting baseline can't silently
    rewrite the numbers under a flag someone has already reviewed), while
    `possible_factors` is recomputed live, so a reviewer opening this
    tomorrow sees current context rather than a stale snapshot."""
    route = flag.route
    carrier = flag.carrier
    flagged_search_date = flag.flagged_search_date.date()
    flagged_travel_date = flag.flagged_travel_date.date()

    return {
        "document_type": DOCUMENT_TYPE,
        "draft_disclaimer": DRAFT_DISCLAIMER,
        "flag_id": flag.id,
        "subject": {
            "carrier_code": flag.carrier_code,
            "carrier_name": carrier.name if carrier else flag.carrier_code,
            "route": route.display_name if route else str(flag.route_id),
            "origin": route.origin if route else "",
            "destination": route.destination if route else "",
            "ap_window_days": flag.ap_window_days,
            "observed_on": flagged_search_date.isoformat(),
            "travel_date_priced": flagged_travel_date.isoformat(),
        },
        "observation": {
            "observed_fare_inr": flag.observed_fare,
            "baseline_median_fare_inr": flag.baseline_median_fare,
            "baseline_mad": flag.baseline_mad,
            "robust_z_score": flag.robust_z_score,
            "pct_above_baseline_median": flag.pct_above_baseline_median,
            "baseline_sample_size": flag.baseline_sample_size,
            "detected_at": flag.detected_at.isoformat() if flag.detected_at else None,
        },
        "detection_method_note": DETECTION_METHOD_NOTE,
        "possible_factors": why_context_for_flag(
            session,
            carrier_code=flag.carrier_code,
            flagged_travel_date=flagged_travel_date,
            flagged_search_date=flagged_search_date,
            gate=gate,
        ),
        "regulator_review": {
            "status": flag.status,
            "review_note": flag.review_note,
            "reviewed_by": flag.reviewed_by,
            "reviewed_at": flag.reviewed_at.isoformat() if flag.reviewed_at else None,
        },
        "boundary_notice": BOUNDARY_NOTICE,
    }
